version: "3.7"
services:
    
    site: 
      build:
        context: ./spa
        dockerfile: Dockerfile
      ports:
        - "10001:80"
      links:
        - api 
      networks:
        - backend
   
    api: 
      build:
        context: ./api
        dockerfile: Dockerfile
      ports:
        - "10000:80"
      environment:
        ASPNETCORE_URLS: http://+:80
        DATABASE_CONN: Server=db;Port=5432;Database=postgres;User Id=postgres;Password=web@1234; 
      links:
        - db
      restart: always
      networks:
        - backend
 
    db: 
      image: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: web@1234 
      restart: always
      networks:
        - backend
  

networks:
  backend:

